
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 17 19:36:05 GMT-05:00 2025
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PALABRA_RESERVADA_PROTECTED = 35;
  public static final int PALABRA_RESERVADA_ARRAYLIST = 19;
  public static final int IDENTIFICADOR = 81;
  public static final int PALABRA_RESERVADA_SUPER = 30;
  public static final int OPERADOR_CORCHETE_CERRAR = 73;
  public static final int LITERAL_CARACTER = 84;
  public static final int PALABRA_RESERVADA_LIST = 18;
  public static final int PALABRA_RESERVADA_WHILE = 5;
  public static final int OPERADOR_RANGO = 48;
  public static final int OPERADOR_MENOR_QUE = 56;
  public static final int OPERADOR_MAYOR_IGUAL_QUE = 57;
  public static final int OPERADOR_ASIGNACION_DIVISION = 63;
  public static final int LITERAL_NUM_FLOTANTE = 83;
  public static final int OPERADOR_OR = 10;
  public static final int PALABRA_RESERVADA_RETURN = 38;
  public static final int PALABRA_RESERVADA_PUBLIC = 33;
  public static final int COMILLA_SIMPLE = 80;
  public static final int OPERADOR_PARENTESIS_ABRIR = 70;
  public static final int OPERADOR_ASIGNACION = 61;
  public static final int PALABRA_RESERVADA_INTERFACE = 24;
  public static final int PALABRA_RESERVADA_PRIVATE = 34;
  public static final int OPERADOR_NOT = 11;
  public static final int OPERADOR_DIVISION = 52;
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_IZQUIERDA = 67;
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_DERECHA = 66;
  public static final int ERROR = 86;
  public static final int OPERADOR_MAYOR_QUE = 55;
  public static final int PALABRA_RESERVADA_IMPORT = 42;
  public static final int LITERAL_STRING = 85;
  public static final int PALABRA_RESERVADA_IMPLEMENTS = 29;
  public static final int COMILLA_DOBLE = 79;
  public static final int PALABRA_RESERVADA_VAR = 43;
  public static final int COMA = 76;
  public static final int PALABRA_RESERVADA_ENUM = 25;
  public static final int PALABRA_RESERVADA_VAL = 44;
  public static final int OPERADOR_DISTINTO = 60;
  public static final int OPERADOR_LLAVE_CERRAR = 75;
  public static final int PALABRA_RESERVADA_IF = 2;
  public static final int PALABRA_RESERVADA_STRING = 17;
  public static final int OPERADOR_PARENTESIS_CERRAR = 71;
  public static final int OPERADOR_DISMINUCION = 54;
  public static final int PALABRA_RESERVADA_STATIC = 36;
  public static final int PALABRA_RESERVADA_SHORT = 16;
  public static final int PALABRA_RESERVADA_OVERRIDE = 37;
  public static final int OPERADOR_FLECHA = 47;
  public static final int PUNTO_Y_COMA = 77;
  public static final int EOF = 0;
  public static final int PUNTO = 78;
  public static final int OPERADOR_DESPLAZAMIENTO_DERECHA = 68;
  public static final int PALABRA_RESERVADA_FOR = 4;
  public static final int PALABRA_RESERVADA_CONST = 45;
  public static final int OPERADOR_ASIGNACION_MULTIPLICACION = 62;
  public static final int PALABRA_RESERVADA_TRY = 40;
  public static final int PALABRA_RESERVADA_WHEN = 6;
  public static final int PALABRA_RESERVADA_INT = 12;
  public static final int PALABRA_RESERVADA_MAP = 20;
  public static final int OPERADOR_IGUAL = 59;
  public static final int error = 1;
  public static final int PALABRA_RESERVADA_TRUE = 7;
  public static final int OPERADOR_DESPLAZAMIENTO_IZQUIERDA = 69;
  public static final int PALABRA_RESERVADA_CATCH = 41;
  public static final int PALABRA_RESERVADA_LONG = 15;
  public static final int PALABRA_RESERVADA_DOUBLE = 22;
  public static final int OPERADOR_INCREMENTO = 53;
  public static final int PALABRA_RESERVADA_EXTENDS = 28;
  public static final int PALABRA_RESERVADA_CHAR = 14;
  public static final int OPERADOR_CORCHETE_ABRIR = 72;
  public static final int OPERADOR_SUSTRACCION = 50;
  public static final int PALABRA_RESERVADA_BOOLEAN = 21;
  public static final int PALABRA_RESERVADA_ABSTRACT = 26;
  public static final int OPERADOR_LLAVE_ABRIR = 74;
  public static final int PALABRA_RESERVADA_VOID = 39;
  public static final int OPERADOR_ASIGNACION_ADICION = 64;
  public static final int PALABRA_RESERVADA_FALSE = 8;
  public static final int OPERADOR_ADICION = 49;
  public static final int PALABRA_RESERVADA_ELSE = 3;
  public static final int OPERADOR_ASIGNACION_SUSTRACCION = 65;
  public static final int PALABRA_RESERVADA_FINAL = 27;
  public static final int OPERADOR_AND = 9;
  public static final int PALABRA_RESERVADA_FLOAT = 13;
  public static final int PALABRA_RESERVADA_NULL = 46;
  public static final int OPERADOR_MENOR_IGUAL_QUE = 58;
  public static final int PALABRA_RESERVADA_THIS = 31;
  public static final int LITERAL_NUM_ENTERO = 82;
  public static final int OPERADOR_MULTIPLICACION = 51;
  public static final int PALABRA_RESERVADA_CLASS = 23;
  public static final int PALABRA_RESERVADA_NEW = 32;
}

